# A.U.R.A - Streamlit Configuration
# This file contains Streamlit configuration for the A.U.R.A dashboard
# Optimized for development and production environments

[global]
# Development settings
developmentMode = true
showErrorDetails = true

[server]
# Server configuration
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

# File watching for development
runOnSave = true
fileWatcherType = "poll"
fileWatcherPollingIntervalSeconds = 1

# Performance settings
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Browser settings
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# A.U.R.A Brand Theme Configuration
# Primary colors from the A.U.R.A color palette
primaryColor = "#00B3B3"  # A.U.R.A Teal
backgroundColor = "#FFFFFF"  # Off-White
secondaryBackgroundColor = "#F8F8F8"  # Light Gray
textColor = "#333333"  # Dark Gray

# Additional theme customization
[theme.base]
# Base theme settings
font = "Lato, Arial, sans-serif"

[logger]
# Logging configuration
level = "debug"
messageFormat = "%(asctime)s.%(msecs)03d [%(name)s] %(levelname)s: %(message)s"
