# A.U.R.A Streamlit Configuration
# Custom theming and configuration for the AURA platform

[theme]
# A.U.R.A Brand Colors - Deep blue and teal theme
primaryColor = "#00B3B3"          # Teal accent color
backgroundColor = "#FFFFFF"        # Clean white background
secondaryBackgroundColor = "#F0F2F6"  # Light gray for cards
textColor = "#262730"            # Dark text for readability
font = "Lato"                     # Modern, clean font

[server]
# Server configuration for Streamlit Cloud
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
# Browser settings
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[logger]
# Logging configuration
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[client]
# Client-side settings
showErrorDetails = true
toolbarMode = "minimal"

[runner]
# Performance settings
magicEnabled = true
installTracer = false
fixMatplotlib = true

[deprecation]
# Disable deprecation warnings for cleaner output
showPyplotGlobalUse = false